### ISSUE TITLE
Incorrect HTTP status code for non-existing pages

### ISSUE THREAD

**Issue by paulroemer** [vaadin/directory#11]
Because of https://github.com/vaadin/flow/issues/13421 the initial response status code is always 200 even if it should be 404.

```
curl -I https://vaadin.com/directory-beta/addon/flow-viritinadasdsad
```

**Comment by samie** [comment]
Seems like a limitation in Hilla and I'm not sure if this is possible in Directory. How is it with other Hilla services like cookbook.vaadin.com?

**Comment by samie** [comment]
This is a general Hilla limitation.
