### ISSUE TITLE
Show only "important" Vaadin versions in the compatibility matrix

### ISSUE THREAD

**Issue by knoobie** [vaadin/directory#2]
^title says it all 😀

This would decrease the information overload by just showing the "important" / "supported" releases in the compatibility matrix like e.g. 14,22,23+ 

Some could argue that the other versions should be accessible.. like some kind of "show more" or remove them all together - I'm fine with both. 

Example: 
![36AD8ED3-9BA3-429B-A905-53B288D6D6D0](https://user-images.githubusercontent.com/3968629/156815494-61f8319a-ca79-4bac-90c4-72e0315d51b9.jpeg)

Taken from here https://directory.demo.vaadin.com/addon/multiselect-combo-box

**Comment by samie** [comment]
Yes, this would improve the readability. One option is is to use similar grouping to https://caniuse.com/?search=DateTimeFormat

**Comment by knoobie** [comment]
That would be awesome!

**Comment by samie** [comment]
Implemented a version of this. How does it feel like?

![compatibility-matrix-collapse-feture](https://user-images.githubusercontent.com/991105/157191337-a134f4b8-4576-4722-ac69-e8ed4c08138b.png)

**Comment by knoobie** [comment]
That looks way better! Thanks a lot
