### ISSUE TITLE
Filtering by author is not working properly

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/directory#3]
If the author name contain spaces, when clicking the hyperlink that navigates to the search with the string "author:A given author" then the search doesn't return results if there are spaces on the name.

**Comment by samie** [comment]
Yes, then search mixes authors to search terms. There is a workaround using underscore `_` instead of space e.g. https://directory.demo.vaadin.com/?q=author%3Astefan_uebe, but the correct way would be to use singe quotes or double quotes, like `author:'Sami Ekblad'  `
