### ISSUE TITLE
Show images as a carousel

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/directory#4]
If a given addon contains several screenshots, when clicking on one of them there is no option for going to the next screenshot.
It would be nice that when the screenshots are shown, you could go to the next one with a carousel.

**Comment by samie** [comment]
Good idea. Then it would be natural to use arrow keys for browsing the images.

**Comment by samie** [comment]
Implemented a version of this. Take a look e.g. at https://directory.demo.vaadin.com/addon/so-charts 
How does it feel like?

**Comment by mlopezFC** [comment]
It feels just right! ... my only comment (but this is something personal) is that maybe it would be better if the < and > buttons are centered vertically.
Great work!

**Comment by mlopezFC** [comment]
And another comment: it would be great that pressing the "Esc" key would close the carousel, what do you think?

**Comment by samie** [comment]
Thanks! That helps.

**Comment by samie** [comment]
This is now deployed. Thanks for the suggestion!
