### ISSUE TITLE
How to detect from server side if client has Popups blocked in Vaadin 14?

### ISSUE THREAD

**Issue by franrolando** [vaadin/directory#44]
I want to know if there is a way to check if popups are blocked in client side and handle it in server side before rendering the view.

**Comment by samie** [comment]
Is this related to [vaadin.com/directory](https://vaadin.com/directory) ? Sounds like it is not, so I just close it.
 
But answering the question: I think the only way to check that is to run try a small asynchronous JavaScript using  `getElement().executeJS(...)` which tries to open a popup and return true/false if that is successful.
