### ISSUE TITLE
Incorrect version ordering in the compatibility matrix

### ISSUE THREAD

**Issue by bwajtr** [vaadin/directory#49]
The version ordering in the compatibility matrix is weird. I'd expect version 23.3.0 to be the rightmost version.
For example here: https://vaadin.com/directory/component/popup

![image](https://github.com/vaadin/directory/assets/1890879/980ba391-294d-4c33-a1ea-5e6ecdcd46af)

**Comment by samie** [comment]
Quickly looking at the code, it seems that this is [because of string sorting](https://github.com/vaadin/directory/blob/main/src/main/java/org/vaadin/directory/endpoint/search/SearchEndpoint.java#L225). I guess there are add-ons that don't follow SemVer, which might be problematic.

**Comment by samie** [comment]
Made a fix in c08f783c0a2e6d074236b22d7cb455e4ad1c37fd should be deployed soon.
