### ISSUE TITLE
Pages for web component addons are not loading

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/directory#5]
Web component addons are not loading. See for instance:
https://directory.demo.vaadin.com/addon/flowingcodefc-applayout
https://directory.demo.vaadin.com/addon/gatanasomultiselect-combo-box

![image](https://user-images.githubusercontent.com/11554739/156897225-a42a139a-1136-4056-bc97-d349dfe21647.png)

Their counterparts in Vaadin Directory work fine:
https://vaadin.com/directory/component/flowingcodefc-applayout
https://vaadin.com/directory/component/gatanasomultiselect-combo-box

**Comment by samie** [comment]
Needs more investigation. Briefly looked into this and it seems to be backend JPA problem. Even data is in db, the version list is empty in component entity which makes the whole UI unavailable. It only happens for web components so, guessing there is data inconsistency somewhere.

**Comment by samie** [comment]
Found the issue and it should be fixed now. However our plan is to hide the web components in the UI and focus only Vaadin compatible add-on.
