### ISSUE TITLE
Dynamically created PDF can Not be exported

### ISSUE THREAD

**Issue by PeterWMundt** [vaadin/directory#51]
In the demo sample (BasicPdfViewerExample) the file (/pdf/example.pdf) is loaded by the class loader (getClass().getResourceAsStream(..)).
And the example works! :-) 
If I create a pdf dynamically (via class PdfCreator uses the Java library pdfbox) and hand it over to the PdfViewer, the file can not be downloaded! 

Any help is appreciated! Thanks! 
[PdfViewer_Issue.zip](https://github.com/vaadin/directory/files/11649743/PdfViewer_Issue.zip)

(Technically spoken: Whether the solution works depends on the implementation of the InputStream.)

**Comment by samie** [comment]
Hey, this repository is for the Directory system itself. I'll close this one, but you might want to report here: https://github.com/vaadin-component-factory/vcf-pdf-viewer-flow/issues
