### ISSUE TITLE
Add 24.4 as supported specific version

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/directory#71]
Directory doesn't allow listing 24.4 as supported specific version of add-ons

![image](https://github.com/vaadin/directory/assets/11554739/4f66a9ba-7c2c-40c2-b4cb-4c6282e24da6)

**Comment by samie** [comment]
Now added. 

<img width="168" alt="directory-24 4" src="https://github.com/vaadin/directory/assets/991105/47b34fd0-54ae-42e0-b2e6-53207d11ad62">

**Comment by javier-godoy** [comment]
The matrix has been updated. Thanks 
![image](https://github.com/user-attachments/assets/6743199d-b920-4f42-8466-c843fd761ace)
